### ISSUE TITLE
Incomplete/broken streams/rivers at municipality borders

### ISSUE THREAD

**Issue by olejorgenb** [NKAmapper/n50osm#1]
`python3 n50osm.py 3427 Arealdekke -stream -ele`

![image](https://user-images.githubusercontent.com/72201/183243362-f724bd47-9916-4549-b0d4-27a4e004deda.png)

**Comment by NKAmapper** [comment]
This river is along a municipality boundary. The missing parts of the river are in the other municipality. Just complete it manually if you are not planning to import the other municipality. Thanks for checking.

**Comment by olejorgenb** [comment]
Ah, :face-palm: Thanks :)

Annoying that the municipality border follows the river (red is the border) :D I guess that's kind common.

![image](https://user-images.githubusercontent.com/72201/183254920-b72135d0-2ab0-498b-80be-24382ee48e1f.png)
